; this is a poc of implementing hello world in RISCX

helloworldstring, 0, 0xffffff, 0, ninsn+0
helloworldstring, 1, 0xffffff, 0, ninsn+1
helloworldstring, 2, 0xffffff, 0, ninsn+2
helloworldstring, 3, 0xffffff, 0, ninsn+3
helloworldstring, 4, 0xffffff, 0, ninsn+4
helloworldstring, 5, 0xffffff, 0, ninsn+5
helloworldstring, 6, 0xffffff, 0, ninsn+6
helloworldstring, 7, 0xffffff, 0, ninsn+7
helloworldstring, 8, 0xffffff, 0, ninsn+8
helloworldstring, 9, 0xffffff, 0, ninsn+9
helloworldstring, 10, 0xffffff, 0, ninsn+10
helloworldstring, 11, 0xffffff, 0, ninsn+11
helloworldstring, 12, 0xffffff, 0, ninsn+12
helloworldstring, 13, 0xffffff, 0, ninsn+13

helloworldstring:
.str "Hello, world!\n"

ninsn:
05
10
15
20
25
30
35
40
45
50
55
60
65
0xffffff
